name: Episodio3
author: PlanetGeeks - Flood
version: 1.0
description: Plugin di prova
main: it.planetgeeks.bukkit.episodio3.Episodio3 

commands:
   tpa:
      description: Richiedi il teletrasporto
      usage: /<command> [player]
      permission: Episodio3.tpa
      permission-message: You don't have <permission>
   tpaccept:
      description: Accetta il teletrasporto
      usage: /<command>
      permission: Episodio3.tpaccept
      permission-message: You don't have <permission>
   tpdeny:
      description: Rifiuta il teletrasporto
      usage: /<command>
      permission: Episodio3.tpdeny
      permission-message: You don't have <permission>
